dist: bionic
language: go

go:
  - 1.x

env:
  global:
  - LANG=C
  - LC_ALL=C

before_cache:
- mountpoint -q $TRAVIS_BUILD_DIR/tmp/mnt && sudo umount -R $TRAVIS_BUILD_DIR/tmp/mnt
- sudo find $TRAVIS_BUILD_DIR/tmp/ -name '*.img' -delete

cache:
  apt: true
  directories:
  - tmp/

before_script:
- sudo apt-get -y update
- sudo apt-get -y install qemu-user-static binfmt-support qemu bmap-tools kpartx
- sudo update-binfmts --display

script:
- sudo -E env "PATH=$PATH" make -e PWN_HOSTNAME="pwnagotchi" VERSION="$TRAVIS_TAG"

# TODO: deploy!
